### ISSUE TITLE
The unloading module has a bug.

### ISSUE THREAD

**Issue by aphage** [tishion/mmLoader#11]
If you load the module, you have no choice to call the module main function. But he will also call it when uninstalling. When no module main function is unloaded, it will crash directly

You should also add the parameters of the main function of the module to be unloaded. It is best to judge whether there is a module main function.

Besides, when no entry point is present, OptionalHeader.AddressOfEntryPoint is zero.
in the CallModuleEntry function

pfnModuleEntry = MakePointer(
        Type_DllMain, 
        pMemModule->lpBase, 
        pImageNtHeader->OptionalHeader.AddressOfEntryPoint);

    if (NULL == pfnModuleEntry)
    {
        pMemModule->dwErrorCode = MMEC_INVALID_ENTRY_POINT;
        return FALSE;
    }

**Comment by tishion** [comment]
@aphage   Reformed this project and fixed this issue.
