### ISSUE TITLE
What if virtual size is more than section alignment when raw size is zero?

### ISSUE THREAD

**Issue by vijaycognore** [tishion/mmLoader#12]
https://github.com/tishion/mmLoader/blob/00648bbcfc0233d71406eb597393e5b6717a7b96/src/mmLoader/mmLoader.cpp#L311

You seem to check if the raw size is zero and if so, we allocate section alignment size. For BCC sections, the raw size is always zero, and virtual size could be much larger (even larger than section alignment). In such cases, we need to allocate the size specified in virtual size and initialize to zero.

**Comment by tishion** [comment]
@vijaycognore  Fixed in https://github.com/tishion/mmLoader/commit/e9e6f5ad850c1dda7cc714b71c9338bdd2b10325
