### ISSUE TITLE
Unable to get export functions of DLL

### ISSUE THREAD

**Issue by CheneyChenStar** [tishion/mmLoader#20]
I don't get export functions of my DLL after used GetMemModuleProc in mmLoader and GetProcAddress in win32 api lib.
when I  used GetMemModuleProc, I found  member of  **NumberOfFunctions** of ExportDirectory is **zero**, but I exported two functions in my DLL.
maybe problem is in **ResolveImportTable** function.

**Comment by tishion** [comment]
Please provide more information.
